services:

  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    entrypoint:
      - /bin/sh
    # run opencloud init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the opencloud server
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      # change to the public domain name of your OpenCloud instance with protocol and port
      OC_URL: https://cloud.opencloud.test:9200 
      OC_LOG_LEVEL: info
      # uncomment if you do not want use SSL between the reverse proxy and OpenCloud
      # PROXY_TLS: "false"
      # INSECURE: needed if OpenCloud is using self generated certificates
      OC_INSECURE: "true"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "false"
      # admin user password
      IDM_ADMIN_PASSWORD: "admin" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "true"
    volumes:
      - opencloud-config:/etc/opencloud
      - opencloud-data:/var/lib/opencloud
    ports:
      - 9200:9200
    logging:
      driver: local
    restart: always

volumes:
  opencloud-config:
  opencloud-data:
